name: Ada (GNAT)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout GCS
      uses: actions/checkout@v4
      with:
        repository: blancolioni/gcs
        path: ./gcs
        
    - name: Checkout Skit
      uses: actions/checkout@v4
      with:
        repository: blancolioni/skit
        path: ./skit
                
    - name: Set up alire
      uses: alire-project/setup-alire@v2
      with:
        version: 2.1.0
        toolchain: gnat_native^15 gprbuild

    - name: Show toolchain
      run: alr toolchain

    - name: Build Leander
      run: alr build
      
    - name: Run tests
      run: ./bin/leander --main=./share/leander/tests/RunTests.hs
      
